global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:4000']

  - job_name: 'auth'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'user'
    static_configs:
      - targets: ['user-service:3001']

  - job_name: 'category'
    static_configs:
      - targets: ['category-service:3001']

  - job_name: 'product'
    static_configs:
      - targets: ['product:3004']

